TASK-3
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #121
Opened 2024-11-07 22:26 UTC by KirillRomancuk

![CBRF_logo svg](https://github.com/user-attachments/assets/cc53bd8d-8cc3-4fd6-9e1c-ee8831e0726e)

2024-11-11 17:44 UTC, andrianovartemii requested changes

2024-11-11 17:44 UTC, andrianovartemii commented on kirill.romanchuk/task-3/strtructs/config/config.go
> +	configFileParse := flag.String("config", "cmd/service/config.yaml", "Path to the configuration file")
Где отображается значение третьего параметра `flag.String`, как его можно посмотреть для бинаря

2024-11-11 17:44 UTC, andrianovartemii commented on kirill.romanchuk/task-3/strtructs/currencyRates/сurrencyRates.go
> +	modifiedContent := strings.ReplaceAll(string(file), ",", ".")
использовать UnmarshalXML для обработки запятых

2024-11-11 17:44 UTC, andrianovartemii commented on kirill.romanchuk/task-3/strtructs/currencyRates/сurrencyRates.go
> +func (c *CurrencyRates) ParseXML(pathToXML string) {
Добавить работу с кодировкой

2024-11-16 16:08 UTC, KirillRomancuk commented on kirill.romanchuk/task-3/strtructs/currencyRates/сurrencyRates.go
> +func (c *CurrencyRates) ParseXML(pathToXML string) {
Добавил

2024-11-16 16:08 UTC, KirillRomancuk commented on kirill.romanchuk/task-3/strtructs/currencyRates/сurrencyRates.go
> +	modifiedContent := strings.ReplaceAll(string(file), ",", ".")
Прикрутил костыль

2024-11-16 21:04 UTC, KirillRomancuk commented on kirill.romanchuk/task-3/strtructs/config/config.go
> +	configFileParse := flag.String("config", "cmd/service/config.yaml", "Path to the configuration file")
![image](https://github.com/user-attachments/assets/d742c95c-54af-43ef-a07e-f4bb5144207e)
По идее так

2024-11-18 15:41 UTC, andrianovartemii commented on kirill.romanchuk/task-3/strtructs/currencyRates/сurrencyRates.go
> +	modifiedContent := strings.ReplaceAll(string(file), ",", ".")
можно было и просто метод переопределить для парсинга, ну да ладно, такое решение тоже подойдет

2024-11-18 15:42 UTC, merged