TASK-3
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #127
Opened 2024-11-10 20:17 UTC by rrevizorr

2024-11-11 17:52 UTC, andrianovartemii requested changes

2024-11-11 17:52 UTC, andrianovartemii commented on alex.udalov/task-3/internal/valuteProcessing/JSONparser.go
> +		return dataJSON, fmt.Errorf("failed to convert to JSON: %w", err)
`dataJson` меняем на `nil`, чтобы не вернуть полузаполненные данные, а использовать пустой указатель

2024-11-11 17:52 UTC, andrianovartemii commented on alex.udalov/task-3/internal/valuteProcessing/XMLparser.go
> +	configFile = []byte(strings.ReplaceAll(string(configFile), ",", "."))
реализовать обработку запятых через метод UnmarshalXML

2024-11-13 14:35 UTC, rrevizorr commented on alex.udalov/task-3/internal/valuteProcessing/JSONparser.go
> +		return dataJSON, fmt.Errorf("failed to convert to JSON: %w", err)
поменял

2024-11-18 15:43 UTC, andrianovartemii approved these changes

2024-11-18 15:43 UTC, merged