[TASK-3]
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #131
Opened 2024-11-11 14:29 UTC by solomonalfred

2024-11-18 18:14 UTC, andrianovartemii requested changes

2024-11-18 18:14 UTC, andrianovartemii commented on nikita.bogdanov/task-3/internal/data_writer/json_writer.go
> +			panic(err)
Поднимаем ошибки до main, здесь и дальше по коду

2024-11-18 18:14 UTC, andrianovartemii commented on nikita.bogdanov/task-3/internal/data_reader/xml_reader.go
> +	stream := []byte(strings.ReplaceAll(string(data), ",", "."))
Переписать на `UnmarshalXML`

2024-11-18 18:14 UTC, andrianovartemii commented on nikita.bogdanov/task-3/internal/data_writer/json_writer.go
> +		err = os.Mkdir(dir, 0755)
использовать MkdirAll для рекурсивного создания директорий

2024-11-25 14:26 UTC, andrianovartemii commented on nikita.bogdanov/task-3/internal/data_writer/json_writer.go
> +			panic(err)
Недоделано

2024-11-25 17:43 UTC, andrianovartemii commented on nikita.bogdanov/task-3/internal/data_reader/xml_reader.go
> +	stream := []byte(strings.ReplaceAll(string(data), ",", "."))
https://pkg.go.dev/encoding/xml#Marshaler

2024-12-02 14:34 UTC, solomonalfred commented on nikita.bogdanov/task-3/internal/data_reader/xml_reader.go
> +	stream := []byte(strings.ReplaceAll(string(data), ",", "."))
Исправил

2024-12-16 16:53 UTC, RomashovVs submitted a review, later dismissed

2024-12-16 19:47 UTC, andrianovartemii approved these changes

2024-12-16 19:49 UTC, andrianovartemii approved these changes

2024-12-16 20:04 UTC, andrianovartemii commented
Принято, но не вливаю, так как есть конфликты

2024-12-16 20:04 UTC, closed without merging