TASK-9
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #216
Opened 2024-12-09 12:35 UTC by Madyarov-Gleb

2024-12-14 17:44 UTC, Madyarov-Gleb commented
## Ответ на вопрос: Разница между Put и Post
Метод Put является идемпотентным, а Post - нет.

2024-12-16 17:25 UTC, MaksimTyanutov requested changes

2024-12-16 17:25 UTC, MaksimTyanutov commented on gleb.madyarov/task-9/internal/handlers/handlers.go
> +	regex := regexp.MustCompile(`^(?:\+7|8)(\d{10})$`)
Вынести regex в глобальную переменную

2024-12-16 17:25 UTC, MaksimTyanutov commented on gleb.madyarov/task-9/internal/handlers/handlers.go
> +	regex := regexp.MustCompile(`^(?:\+7|8)(\d{10})$`)
Не очень корректная обработка телефонного номера.

Пример: +7123456789----------0

2024-12-16 17:40 UTC, MaksimTyanutov approved these changes

2024-12-16 17:41 UTC, merged