TASK-2-1
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #32
Opened 2024-10-06 11:35 UTC by Madyarov-Gleb

2024-10-13 23:50 UTC, andrianovartemii requested changes
Переписать без срезов

2024-10-14 17:37 UTC, MaksimTyanutov commented
Граничные условия кондиционера не учтены (>=15 <=30)

Сама программа работает корректно. Если условия добавлены можно принимать.

2024-10-14 20:08 UTC, MaksimTyanutov submitted a review, later dismissed
Ошибку для граничных условий можно было бы и подробнее расписать (например, написать какие граничные условия)

2024-10-21 17:20 UTC, KorolevDenis approved these changes

2024-10-28 14:26 UTC, andrianovartemii approved these changes

2024-10-28 14:26 UTC, merged