Task-1
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #34
Opened 2024-10-06 16:15 UTC by artem6554

Я забыл изначально в отдельной ветке всё делать, поэтому тут произошло немного смешных вещей, извиняюсь

2024-10-07 15:44 UTC, Bogdan-Denisenko commented on mesropyan.artyom/task-1/cmd/service/task-1.go
https://github.com/lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu#:~:text=%D0%9A%D0%B0%D0%B6%D0%B4%D1%8B%D0%B9%20%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%20%D0%B2%20PR%20%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%20%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%82%D1%8C%20%D0%B7%D0%B0%D0%BA%D0%BE%D0%BD%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.%20%D0%92%20%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8%20%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%B3%D0%BE%20%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%B0%20%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D0%B2%20%D0%BA%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82%D0%BD%D1%8B%D1%85%20%D1%81%D0%BA%D0%BE%D0%B1%D0%BA%D0%B0%D1%85%20%D0%B8%20%D0%BA%D1%80%D0%B0%D1%82%D0%BA%D0%BE%D0%B5%20%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%B2%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%BD%D1%8B%D1%85%20%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9%20%D0%BD%D0%B0%20%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%BE%D0%BC%20%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5.

2024-10-07 15:55 UTC, Bogdan-Denisenko commented on mesropyan.artyom/task-1/cmd/service/task-1.go
читать `Требования к публикации практических работ` пункт 4

2024-10-07 16:01 UTC, MaksimTyanutov commented
Можно сразу ввести все необходимые данные и программа преждевременно завершится
```
Введите первое число: 1 + 1
Выберите операцию (+, -, *, /): Введите второе число: Результат 1 + 1 = 2
```

2024-10-13 23:43 UTC, andrianovartemii requested changes
читать Требования к публикации практических работ пункт 4

2024-10-14 17:31 UTC, artem6554 commented
> читать Требования к публикации практических работ пункт 4

Вроде как исправил

2024-10-14 20:51 UTC, MaksimTyanutov approved these changes

2024-10-14 20:53 UTC, MaksimTyanutov approved these changes

2024-10-21 16:14 UTC, andrianovartemii approved these changes

2024-10-21 16:14 UTC, merged