TASK-2-1
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #59
Opened 2024-10-13 17:13 UTC by Isterd

2024-10-14 16:55 UTC, andrianovartemii requested changes

2024-10-14 16:55 UTC, andrianovartemii commented on erdem.istaev/task-2-1/internal/errors/errors.go
Файл нужно разложить по пакетам, чтобы в каждом пакете было `errors.go` и там содержались ошибки, характерные именно для этого пакета

2024-10-21 16:09 UTC, andrianovartemii commented on README.md
> -## Правила оформления практических работы
Если это сделано через `--amend`, то лучше удалить (об этом можно просто написать мне, если есть какие-то опечатки)

2024-10-21 16:17 UTC, Isterd commented on README.md
> -## Правила оформления практических работы
я же правильно понял, что этого файла не должно быть в изменениях в моей ветке, сделал rebase

2024-10-21 17:27 UTC, andrianovartemii approved these changes

2024-10-21 17:27 UTC, merged