TASK-2-1
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #82
Opened 2024-10-19 20:39 UTC by katagiriwhy

2024-10-21 16:42 UTC, andrianovartemii requested changes

2024-10-21 16:42 UTC, andrianovartemii commented on danil.novokhatskiy/task-2-1/internal/computeTemperature.go
> +		fmt.Println(-1)
вынести это в `main.go`, тут прокидывать ошибку

2024-10-21 17:43 UTC, andrianovartemii requested changes

2024-10-21 17:43 UTC, andrianovartemii commented on danil.novokhatskiy/task-2-1/internal/computeTemperature.go
> +		fmt.Println(*minTemp)
возвращать через return

2024-10-23 17:32 UTC, RomashovVs commented on danil.novokhatskiy/task-2-1/cmd/service/main.go
> +	if countDepartments <= 0 || countDepartments > 1000 || err != nil {
Магические числа - в константы.

2024-10-23 17:33 UTC, RomashovVs commented on danil.novokhatskiy/task-2-1/cmd/service/main.go
> +		if countWorkers <= 0 || countWorkers > 1000 || err != nil {
Магические числа - в константы.

2024-10-23 17:33 UTC, RomashovVs commented on danil.novokhatskiy/task-2-1/internal/computeTemperature.go
> +	maxTemp := 30
Лучше вынести их из функции, либо передавать. Либо использовать константы.

2024-10-28 14:21 UTC, merged