TASK-2-2
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #83
Opened 2024-10-20 14:39 UTC by Gburan

2024-10-21 16:57 UTC, andrianovartemii requested changes

2024-10-21 16:57 UTC, andrianovartemii commented on zhukov.gleb/task-2-2/internal/lunch/lunch.go
> +			continue
обрабатывать их лучше в main.go, потому что там точка входа
лучше не перемешивать log и fmt

2024-10-21 16:58 UTC, andrianovartemii commented on zhukov.gleb/task-2-2/internal/lunch/lunch.go
> +type ConsoleLunch struct{}
можно передавать reader как зависимость через `NewConsoleLunch`, тогда можно будет менять

2024-10-21 17:00 UTC, andrianovartemii commented on zhukov.gleb/task-2-2/internal/reader/reader.go
> +	input, err := reader.ReadString('\n')
Нужно уметь читать и из строки разделенной пробелами

2024-10-21 17:05 UTC, andrianovartemii requested changes
не работает с -10 и 1001 значениями для температуры

2024-10-26 15:10 UTC, Gburan commented
> не работает с -10 и 1001 значениями для температуры

Температуры - 2.1 лаба. В ней эти значения работают

2024-10-28 14:37 UTC, merged