TASK-2-1
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #85
Opened 2024-10-20 21:21 UTC by hahapathetic

2024-10-21 17:09 UTC, andrianovartemii requested changes

2024-10-21 17:09 UTC, andrianovartemii commented on alina.mamonova/task-2-1/cmd/service/main.go
> +		employeesNum := input.ProcessNumInput("Enter the number of employees: ")
`calculateOptimalTemp` и читает температуру, и отделы, и сотрудников
нужно передавать сюда `reader`

2024-10-28 14:50 UTC, andrianovartemii commented
Вышел дедлайн сдачи работ, PR закрываю

2024-10-28 17:19 UTC, AnnDutova commented
- [ ] замечание про `reader`  для методов Process*Input все еще не пофикшено

2024-10-28 18:03 UTC, hahapathetic commented
@AnnDutova

2024-11-04 17:51 UTC, AnnDutova approved these changes

2024-11-04 18:02 UTC, andrianovartemii approved these changes

2024-11-04 18:03 UTC, merged