TASK-2-2
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #86
Opened 2024-10-20 21:25 UTC by hahapathetic

2024-10-21 17:13 UTC, andrianovartemii requested changes

2024-10-21 17:13 UTC, andrianovartemii commented on alina.mamonova/task-2-2/internal/heap-handler/heap_handler.go
> +	k := input.ProcessNumInput("Enter the k: ", 1, size)
нужно вынести из этой функции, она должна принмать это как параметр

2024-10-21 17:17 UTC, andrianovartemii requested changes
ввод с отдельных строк, в задании с одной строки

2024-10-28 14:49 UTC, andrianovartemii commented
Вышел дедлайн сдачи работ, PR закрываю

2024-10-28 16:55 UTC, andrianovartemii commented
амнистия от @AnnDutova, ей и проверять :)

2024-10-28 18:03 UTC, hahapathetic commented
@AnnDutova

2024-11-04 18:03 UTC, andrianovartemii approved these changes

2024-11-04 18:03 UTC, merged