TASK-2-1
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #87
Opened 2024-10-21 10:28 UTC by rrevizorr

2024-10-21 16:55 UTC, KorolevDenis requested changes
Нарушены требования 2 и 4 к публикации практических работ

2024-10-21 17:05 UTC, RomashovVs commented on alex.udalov/task-2-2/cmd/service/main.go
> +			continue
Исправить на ошибку. Чтобы было видно непринятый ввод. Не всегда бесконечный ввод - это хорошо :)

2024-10-23 17:11 UTC, RomashovVs commented on alex.udalov/task-2-2/cmd/service/main.go
> +			continue
Перенести в новый ПР.

2024-10-23 17:27 UTC, RomashovVs commented on alex.udalov/task-2-1/internal/analyzer/analyzer.go
> +	if err != nil || k > 30 || k < 15 || (oper != ">=" && oper != "<=") {
В константы.

2024-10-23 17:27 UTC, RomashovVs commented on alex.udalov/task-2-1/internal/analyzer/analyzer.go
> +	if err != nil || n < 1 || n > 1000 {
Константы.

2024-10-23 17:28 UTC, RomashovVs commented on alex.udalov/task-2-1/internal/temperature/temperature.go
> +		minTemp: 15,
Поместить константы, которые создашь.

2024-10-25 15:30 UTC, rrevizorr commented
> Нарушены требования 2 и 4 к публикации практических работ

Исправил.

2024-10-26 10:00 UTC, RomashovVs approved these changes

2024-10-26 16:51 UTC, KorolevDenis approved these changes
Требование 4 к публикации все еще нарушено, есть коммиты

2024-10-26 16:52 UTC, merged