TASK-2-1
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #88
Opened 2024-10-21 12:42 UTC by solomonalfred

2024-10-21 17:28 UTC, RomashovVs commented on nikita.bogdanov/task-2-1/internal/app.go
> +		lowBoundTemp := 15
Вынести в константы - магические числа.

2024-10-21 17:28 UTC, RomashovVs commented on nikita.bogdanov/task-2-1/internal/app.go
> +)
Последовательность импортов/новая строка.

В каждом файле.

2024-10-21 17:30 UTC, RomashovVs commented on nikita.bogdanov/task-2-1/internal/app.go
> +				writer.Write_optional_temperature(out, -1)
snake_case

2024-10-21 17:36 UTC, andrianovartemii requested changes

2024-10-21 17:36 UTC, andrianovartemii commented on nikita.bogdanov/task-2-1/internal/app.go
`app.go` должен быть в пакете `internal/app`

2024-10-28 13:41 UTC, solomonalfred commented on nikita.bogdanov/task-2-1/internal/app.go
всё исправил

2024-10-28 14:32 UTC, andrianovartemii commented on nikita.bogdanov/task-2-1/internal/app.go
> +				writer.Write_optional_temperature(out, -1)
@solomonalfred, Не исправлено, в будущем внимательнее

2024-10-28 14:33 UTC, andrianovartemii approved these changes

2024-10-28 14:33 UTC, merged