TASK-2-2
lets-go-programming-contest/lets-go-programming-v2024-autumn-spbstu pull request #89
Opened 2024-10-21 14:00 UTC by solomonalfred

2024-10-21 17:39 UTC, KorolevDenis commented on nikita.bogdanov/task-2-2/internal/app.go
> +	"task-2-2/internal/reader"
Последовательность импортов/новая строка.

В каждом файле.

2024-10-21 17:39 UTC, KorolevDenis commented on nikita.bogdanov/task-2-2/internal/reader/data_reader.go
> +		if meal < -10000 || meal > 10000 {
В константы

2024-10-21 17:39 UTC, andrianovartemii requested changes

2024-10-28 13:51 UTC, solomonalfred commented on nikita.bogdanov/task-2-2/internal/app.go
> +	defer output.Flush()
Всё пофиксил

2024-10-28 14:34 UTC, andrianovartemii approved these changes

2024-10-28 14:34 UTC, merged